services:
  - type: web
    name: bank-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn bank_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_NAME
        value: bankdb
      - key: DB_USER
        value: bankuser
      - key: DB_PASSWORD
        value: your_password
      - key: DB_HOST
        value: your-hostname
